### ISSUE TITLE
Safety warnings about the dependencies in GitHub Actions

### ISSUE THREAD

**Issue by MrWillCom** [transmister/transmister-client-android#3]
I saw the action called "Linter", it looks like is based on [axel-op/googlejavaformat-action](https://github.com/axel-op/googlejavaformat-action). It has only 12 stars, are you sure it is safe?

[transmister/transmister-server-and-web](https://github.com/transmister/transmister-server-and-web) only use trusted dependencies, like socket.io, Next.js, React, mongoose... You can check its [package.json](https://github.com/transmister/transmister-server-and-web/blob/master/package.json). 

**Be careful with [Supply chain attacks](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/supply-chain-malware)!**

**Comment by aeilot** [comment]
I'm pretty sure about the safety.

**Comment by MrWillCom** [comment]
> I'm pretty sure about the safety.

But it only has 12 stars! How can you prove it is safe?

To make sure with its safety, you need to check **all** the **source code**!

**Comment by aeilot** [comment]
I've already checked the code!

**Comment by MrWillCom** [comment]
**Please don't close this issue before you check its source code or remove it from this project.**

**Comment by aeilot** [comment]
F**k u

**Comment by aeilot** [comment]
Check:
```
const executable = path.join(process.env.HOME || process.env.USERPROFILE, 'google-java-format.jar');
const apiReleases = 'https://api.github.com/repos/google/google-java-format/releases';
```

**Comment by MrWillCom** [comment]
**Tip: JetBrains IDE, Visual Studio Code and many editors can format your code.**

**Comment by aeilot** [comment]
I know this

**Comment by aeilot** [comment]
```
async function run() {
    try {
        // Get Google Java Format executable and save it to [executable]
        const releaseId = await getReleaseId();
        await core.group('Downloading Google Java Format', async () => {
            const urlRelease = `${apiReleases}/${releaseId}`;
            core.debug(`URL: ${urlRelease}`);
            let release = await execute(`curl -s "${urlRelease}"`, { silent: true });
            release = JSON.parse(release.stdOut);
            core.debug(`release is ${typeof release}`);
            const assets = release['assets'];
            core.debug(`assets is ${typeof assets}`);
            const downloadUrl = assets.find(asset => asset['name'].endsWith('all-deps.jar'))['browser_download_url'];
            core.info(`Downloading executable to ${executable}`);
            await execute(`curl -sL ${downloadUrl} -o ${executable}`, { silent: !core.isDebug() });
            await executeGJF(['--version']);
        });

        // Execute Google Java Format with provided arguments
        const args = core.getInput('args').split(' ');
        core.debug(`Arguments: ${args}`);
        const files = await (await glob.create(core.getInput('files'))).glob();
        core.debug(`Files:`);
        for (const file of files) {
            core.debug(`* ${file}`);
            args.push(file);
        }
        await executeGJF(args);

        // Commit changed files if there are any and if skipCommit != true
        if (core.getInput('skipCommit').toLowerCase() !== 'true') {
            await core.group('Committing changes', async () => {
                await execute('git config user.name github-actions', { silent: true });
                await execute("git config user.email ''", { silent: true });
                const diffIndex = await execute('git diff-index --quiet HEAD', { ignoreReturnCode: true, silent: true });
                if (diffIndex.exitCode !== 0) {
                    await execute('git commit --all -m "Google Java Format"');
                    await execute('git push');
                } else core.info('Nothing to commit!')
            });
        }
    } catch (message) {
        core.setFailed(message);
    }
}
```

**Comment by aeilot** [comment]
What the script does is:
Download the Google's Linter => Lint

**Comment by aeilot** [comment]
You should always trust an Open Source Project as other people trust us while our project may be lack of star.

**Comment by MrWillCom** [comment]
> Check:
> 
> ```js
> const executable = path.join(process.env.HOME || process.env.USERPROFILE, 'google-java-format.jar');
> const apiReleases = 'https://api.github.com/repos/google/google-java-format/releases';
> ```

So why don't you use it directly?

**Comment by MrWillCom** [comment]
**Use as few dependencies as possible!**

**Comment by aeilot** [comment]
This is not a dependency in our project!

**Comment by aeilot** [comment]
Alright! Stop NOW! And FOCUS ON YOUR PROJECT!

**Comment by MrWillCom** [comment]
**Focus on SAFETY!!!** It's why we do this!

**Comment by MrWillCom** [comment]
I've checked its actions [here](https://github.com/transmister/transmister-client-android/runs/934607563), it's safe! Also, I starred it!
